name: TeaTest CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download

    - name: Build
      run: |
        go build -v -o teatest ./main.go
        mkdir -p release
        mv teatest release/

    - name: Test
      run: go test -v ./...
