name: TeaTest CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GO_VERSION: '1.21'
  NODE_VERSION: '18'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Clean and Verify Modules
      run: |
        # Modül cache temizliği
        go clean -modcache
        
        # go.sum varsa sil (yeniden oluşturmak için)
        if [ -f go.sum ]; then
          rm go.sum
        fi
        
        # Sadece go.mod yoksa init yap
        if [ ! -f go.mod ]; then
          go mod init github.com/esduez/TeaTest
        fi
        
        # Bağımlılıkları güncelle
        go mod tidy
        go mod download
        go mod verify

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Binary
      run: |
        go build -v -o teatest .
        mkdir -p release
        mv teatest release/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Tests
      run: go test -v ./...

  release:
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Publish to NPM
      run: npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
