name: TeaTest CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GO_VERSION: '1.21'
  NODE_VERSION: '18'

jobs:
  verify_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Force Correct Dependencies
      run: |
        # Tüm cache'leri temizle
        go clean -modcache
        rm -f go.sum
        
        # Manuel olarak doğru versiyonları yükle
        go get github.com/inconshreveable/mousetrap@v1.1.0
        go get github.com/spf13/cobra@v1.7.0
        
        # Modülleri senkronize et
        go mod tidy
        go mod download
        go mod verify

    - name: Build
      run: |
        go build -v -o teatest .
        mkdir -p release
        mv teatest release/

  test:
    needs: verify_and_build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Tests
      run: go test -v ./...

  release:
    needs: [verify_and_build, test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Publish to NPM
      run: |
        npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
