name: Publish to Tea.xyz
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Tea CLI (Guaranteed)
        run: |
          # Tea CLI'yi kök dizine kuruyoruz
          curl -fsSL https://tea.xyz/install.sh | sh -s -- --yes --prefix=/usr/local
          echo "/usr/local/tea/tea.xyz/v*/bin" >> $GITHUB_PATH
          echo "PATH=/usr/local/tea/tea.xyz/v*/bin:$PATH" >> $GITHUB_ENV
          
     
